# Fastfile for Watch the Corners. This will speed up deployment of the game.
fastlane_version '0.3.0'

before_all do
  update_fastlane
  ensure_git_status_clean
  increment_build_number
  xcclean
end

lane :major do
  increment_version_number(
    bump_type: 'major'
  )
  commit_version_bump
end

lane :minor do
  increment_version_number(
    bump_type: 'minor'
  )
  commit_version_bump
end

lane :patch do
  increment_version_number
  commit_version_bump
end

lane :deploy do
  add_git_tag(
    grouping: 'releases',
    prefix: 'v'
  )
  ipa({
        workspace: 'Watch The Corners.xcworkspace',
        configuration: 'Release',
        scheme: 'Watch The Corners',
        clean: true,
        destination: './build/ipa',
        ipa: 'WatchTheCorners.ipa'
      })
  sigh
  deliver(
    skip_deploy: true,
    force: true
  )
end

lane :crashlytics do
  ipa({
        workspace: 'Watch The Corners.xcworkspace',
        configuration: 'Release',
        scheme: 'Watch The Corners',
        clean: true,
        destination: './build/ipa',
        ipa: 'WatchTheCorners.ipa'
      })
  sigh
  crashlytics({
                crashlytics_path: './Crashlytics.framework',
                api_token: '...',
                build_secret: '...',
                ipa_path: './app.ipa'
              })
end

lane :testflight do
  ipa({
        workspace: 'Watch The Corners.xcworkspace',
        configuration: 'Release',
        scheme: 'Watch The Corners',
        clean: true,
        destination: './build/ipa',
        ipa: 'WatchTheCorners.ipa'
      })
  sigh
  deliver(
    beta: true,
    force: true
  )
end

after_all do |lane|
  clean_build_artifacts
  slack(
    message: "Deployed a #{lane} update for Watch The Corners.",
    success: true
  )
  notify "Finished running #{lane}!"
end

error do |lane, exception|
  slack(
    message: "Error deploying a #{lane} update for Watch the Corners, caused by #{exception}",
    success: false
  )
  notify "Error running #{lane}."
end
