# Fastfile for Watch the Corners. This will speed up deployment of the game.
fastlane_version '0.3.0'

before_all do
  ENV['SLACK_URL'] = 'https://hooks.slack.com/services/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'

  increment_build_number

  ipa({
    workspace: 'Watch The Corners.xcworkspace',
    configuration: 'Debug',
    scheme: 'Watch The Corners'
  })

  xctool
end

lane :test do
  snapshot
end

lane :beta do
  snapshot
  sigh
  deliver :skip_deploy, :beta

end

lane :deploy do
  snapshot
  sigh
  deliver :skip_deploy, :force
  frameit
end

after_all do |lane|
  slack({
    message: "Successfully deployed an update for Watch The Corners via #{lane}",
    success: true
  })
end

error do |lane, exception|
  slack({
    message: "Error deploying your update for Watch the Corners via #{lane}, caused by #{exception}",
    success: false
    })
end
