# Fastfile for Watch the Corners. This will speed up deployment of the game.
fastlane_version '0.3.0'

before_all do
  ensure_git_status_clean

  increment_build_number

  xcclean
end

lane :major do
  increment_version_number 'major'
  ipa({
        workspace: 'Watch The Corners.xcworkspace',
        configuration: 'Release',
        scheme: 'Watch The Corners',
        clean: true,
        destination: './build/ipa',
        ipa: 'WatchTheCorners.ipa'
      })
  sigh
  deliver :skip_deploy, :force
end

lane :minor do
  increment_version_number 'minor'
  ipa({
        workspace: 'Watch The Corners.xcworkspace',
        configuration: 'Release',
        scheme: 'Watch The Corners',
        clean: true,
        destination: './build/ipa',
        ipa: 'WatchTheCorners.ipa'
      })
  sigh
  deliver :skip_deploy, :force
end

lane :patch do
  increment_version_number
  ipa({
        workspace: 'Watch The Corners.xcworkspace',
        configuration: 'Release',
        scheme: 'Watch The Corners',
        clean: true,
        destination: './build/ipa',
        ipa: 'WatchTheCorners.ipa'
      })
  sigh
  deliver :skip_deploy, :force
end

after_all do |lane|
  clean_build_artifacts
  commit_version_bump(
    message: "New #{lane} version built and submitted."
  )
  slack({
          message: "Deployed a #{lane} update for Watch The Corners.",
          success: true
        })
  notify "Finished running #{lane}!"
end

error do |lane, exception|
  slack({
          message: "Error deploying a #{lane} update for Watch the Corners, caused by #{exception}",
          success: false
        })
  notify "Error running #{lane}."
end
