# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
  'iPhone 6',
  'iPhone 6 Plus',
  'iPhone 5s'
])

languages([
  'en-US'
])

# Where should the resulting screenshots be stored?
screenshots_path './screenshots'

clear_previous_screenshots # remove the '#'' to clear all previously generated screenshots before creating new ones

# JavaScript UIAutomation file
js_file './snapshot.js'

# The name of the project's scheme
scheme 'Watch The Corners'

# Where is your project (or workspace)? Provide the full path here
project_path '../Watch The Corners.xcworkspace'
